### ISSUE TITLE
offtopic issue about Pascal

### ISSUE THREAD

**Issue by Alexey-T** [GuvaCode/RayEngine#1]
@GuvaCode can I ask you to write some Pascal code for my text editor, for donation? I wanted that the PHP lexer has the internal code-tree parser, currently such parser exists in Python and I wanted it in Pascal. this parser must only do this - find the function/class declarations and return list of declarations + nesting levels.

**Comment by Alexey-T** [comment]
Will be like this code
https://github.com/Alexey-T/CudaText/blob/master/app/treehelper_markdown.pas

**Comment by GuvaCode** [comment]
Алексей как я понял ты хочешь анализатор кода (функций и процедур) для паскаля?

**Comment by Alexey-T** [comment]
Анализатор языка PHP (там реально надо искать в кусках внутре тега `<?    ?>`) написанный на паскале.

**Comment by GuvaCode** [comment]
Ну можно заняться. Что подобное делал для анализа markdown. Только по времени не могу сказать как быстро.

**Comment by Alexey-T** [comment]
хорошо. я могу показать вот этот код который уже все делает - он на питоне и я хочу "такое же на паскале".
https://sourceforge.net/projects/cudatext/files/addons/treehelpers/treehelper.PHP.zip/download

**Comment by Alexey-T** [comment]
Он ищет вот такие три штуки-
```

    if s=='class':
        return 1
    if s=='function':
        return 5
    if s=='trait':
        return 2
    return 0
```

**Comment by GuvaCode** [comment]
Ладно завтра вечером после работы займусь.

**Comment by Alexey-T** [comment]
предлагаю символический donate - 1500р.

**Comment by Alexey-T** [comment]
Окей, если все же надумаете, дайте мне знать, например можно тут обсудить
https://github.com/Alexey-T/CudaText

**Comment by GuvaCode** [comment]
Привет. Пока завал на работе ухожу в 7,домой прихожу в 23:00

**Comment by Alexey-T** [comment]
А, понятно-- ну да, работа сначала, а хобби потом
